"""add dev_preview_url to project_repos

Revision ID: 1832bfac2bd1
Revises: acdf6dc8040f
Create Date: 2026-03-23 11:09:46.157270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1832bfac2bd1'
down_revision: Union[str, Sequence[str], None] = 'acdf6dc8040f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_repos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dev_preview_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_repos', schema=None) as batch_op:
        batch_op.drop_column('dev_preview_url')

    # ### end Alembic commands ###
