"""add doc link fields to tasks

Revision ID: 70995646c278
Revises: 0fde09830f02
Create Date: 2026-03-17 16:00:53.673516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70995646c278'
down_revision: Union[str, Sequence[str], None] = '0fde09830f02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prd_doc_platform', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('prd_doc_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tech_doc_platform', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tech_doc_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('tech_doc_url')
        batch_op.drop_column('tech_doc_platform')
        batch_op.drop_column('prd_doc_url')
        batch_op.drop_column('prd_doc_platform')

    # ### end Alembic commands ###
