"""add dev_command and dev_port to project_repos

Revision ID: acdf6dc8040f
Revises: c4a91f3b2e05
Create Date: 2026-03-20 16:58:04.113472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acdf6dc8040f'
down_revision: Union[str, Sequence[str], None] = 'c4a91f3b2e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_repos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dev_command', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('dev_port', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_repos', schema=None) as batch_op:
        batch_op.drop_column('dev_port')
        batch_op.drop_column('dev_command')

    # ### end Alembic commands ###
