"""add sub_path to project_repos

Revision ID: f00cf03a47c7
Revises: c4a91f3b2e05
Create Date: 2026-03-19 21:25:44.269280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f00cf03a47c7'
down_revision: Union[str, Sequence[str], None] = 'c4a91f3b2e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_repos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_path', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_repos', schema=None) as batch_op:
        batch_op.drop_column('sub_path')

    # ### end Alembic commands ###
