import uuid
from datetime import datetime, timezone
from enum import IntEnum

from sqlalchemy import (
    Column,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import DeclarativeBase, relationship


class TaskStatus(IntEnum):
    CREATED = 0
    INITIALIZING = 1
    PLANNING = 2
    PLAN_LOCKED = 3
    TODO_READY = 4
    CODING = 5
    REVIEWING = 6
    DONE = 7


class TodoStatus(IntEnum):
    PENDING = 0
    RUNNING = 1
    DONE = 2
    FAILED = 3
    SKIPPED = 4


class SessionStatus(IntEnum):
    WAITING = 0
    RUNNING = 1
    DONE = 2
    FAILED = 3


def _uuid() -> str:
    return uuid.uuid4().hex


def _now() -> datetime:
    return datetime.now(timezone.utc)


class Base(DeclarativeBase):
    pass


class RunnerConfig(Base):
    """Agent runner configuration. Each record is a named, typed runner with its own credentials."""
    __tablename__ = "runner_configs"

    id = Column(String, primary_key=True, default=_uuid)
    type = Column(String, nullable=False)   # "cody" | "claude_code" | "cursor"
    name = Column(String, nullable=False)   # user-visible display name
    config = Column(Text, default="{}")     # JSON: type-specific credentials
    created_at = Column(DateTime, default=_now)
    updated_at = Column(DateTime, default=_now, onupdate=_now)


class Project(Base):
    __tablename__ = "projects"

    id = Column(String, primary_key=True, default=_uuid)
    name = Column(String, nullable=False)
    description = Column(Text, default="")
    runner_id = Column(String, ForeignKey("runner_configs.id", ondelete="SET NULL"), nullable=True)
    created_at = Column(DateTime, default=_now)
    updated_at = Column(DateTime, default=_now, onupdate=_now)

    repos = relationship("ProjectRepo", back_populates="project", cascade="all, delete-orphan")
    tasks = relationship("Task", back_populates="project", cascade="all, delete-orphan")
    conversations = relationship("Conversation", back_populates="project", cascade="all, delete-orphan")
    project_skills = relationship("ProjectSkill", cascade="all, delete-orphan")


class ProjectRepo(Base):
    __tablename__ = "project_repos"

    id = Column(String, primary_key=True, default=_uuid)
    project_id = Column(String, ForeignKey("projects.id", ondelete="CASCADE"), nullable=False, index=True)
    git_url = Column(String, default="")
    local_path = Column(String, default="")
    repo_type = Column(String, default="custom")  # frontend / backend / custom
    repo_type_label = Column(String, default="")
    description = Column(Text, default="")
    sub_path = Column(String, default="")  # focus subdirectory within the repo (empty = whole repo)
    master_hash = Column(String, default="")  # last known master/main HEAD hash
    created_at = Column(DateTime, default=_now)

    project = relationship("Project", back_populates="repos")


class Task(Base):
    __tablename__ = "tasks"

    id = Column(String, primary_key=True, default=_uuid)
    name = Column(String, nullable=False)
    project_id = Column(String, ForeignKey("projects.id", ondelete="CASCADE"), nullable=False, index=True)
    description = Column(Text, default="")
    branch = Column(String, default="")
    prd = Column(Text, default="")
    prd_doc_url = Column(String, default="")
    prd_images = Column(Text, default="[]")  # JSON array of image file paths
    tech_plan = Column(Text, default="")
    tech_doc_url = Column(String, default="")
    spec_doc = Column(Text, default="")  # functional specification (generated by spec agent)
    status = Column(Integer, default=0)  # 0=created..7=done
    mr_info = Column(Text, default="{}")  # JSON
    runner_id = Column(String, ForeignKey("runner_configs.id", ondelete="SET NULL"), nullable=True)
    created_at = Column(DateTime, default=_now)
    updated_at = Column(DateTime, default=_now, onupdate=_now)

    project = relationship("Project", back_populates="tasks")
    todos = relationship("Todo", back_populates="task", cascade="all, delete-orphan")
    task_skills = relationship("TaskSkill", cascade="all, delete-orphan")


class Todo(Base):
    __tablename__ = "todos"

    id = Column(String, primary_key=True, default=_uuid)
    task_id = Column(String, ForeignKey("tasks.id", ondelete="CASCADE"), nullable=False, index=True)
    seq = Column(Integer, nullable=False)
    title = Column(String, default="")
    description = Column(Text, default="")
    status = Column(Integer, default=0)  # 0=pending,1=running,2=done,3=failed,4=skipped
    cody_session_id = Column(String, nullable=True)
    commit_before = Column(Text, default="")  # JSON: {"repo_path": "hash", ...}
    commit_after = Column(Text, default="")   # JSON: {"repo_path": "hash", ...}
    result = Column(Text, default="")
    created_at = Column(DateTime, default=_now)
    updated_at = Column(DateTime, default=_now, onupdate=_now)

    task = relationship("Task", back_populates="todos")


class Session(Base):
    __tablename__ = "sessions"

    session_id = Column(String, primary_key=True)  # business ID like task:42:plan
    task_id = Column(String, ForeignKey("tasks.id", ondelete="SET NULL"), nullable=True, index=True)
    cody_session_id = Column(String, nullable=True)
    type = Column(String, nullable=False)  # init/plan/todo_split/todo_exec/review
    ref_id = Column(String, default="", index=True)
    layer = Column(Integer, nullable=True)  # 1-4 for init, NULL otherwise
    status = Column(Integer, default=0)  # 0=waiting,1=running,2=done,3=failed
    error = Column(Text, nullable=True)
    started_at = Column(DateTime, nullable=True)
    finished_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=_now)


class ConversationStatus(IntEnum):
    CREATING = 0   # init in progress (copying code, syncing skills)
    READY = 1      # can chat
    FAILED = 2     # init failed


class Conversation(Base):
    __tablename__ = "conversations"

    id = Column(String, primary_key=True, default=_uuid)
    name = Column(String, nullable=False)
    project_id = Column(String, ForeignKey("projects.id", ondelete="CASCADE"), nullable=False, index=True)
    description = Column(Text, default="")
    status = Column(Integer, default=0)  # ConversationStatus
    runner_id = Column(String, ForeignKey("runner_configs.id", ondelete="SET NULL"), nullable=True)
    created_at = Column(DateTime, default=_now)
    updated_at = Column(DateTime, default=_now, onupdate=_now)

    project = relationship("Project", back_populates="conversations")


class JobRunStatus(IntEnum):
    RUNNING = 0
    SUCCESS = 1
    FAILED = 2


class Job(Base):
    """Job definition — what type of job, which project, config."""
    __tablename__ = "jobs"

    id = Column(String, primary_key=True, default=_uuid)
    project_id = Column(String, ForeignKey("projects.id", ondelete="CASCADE"), nullable=False, index=True)
    type = Column(String, nullable=False)       # "repo_monitor" (extensible)
    enabled = Column(Integer, default=1)         # 1=enabled, 0=disabled
    interval = Column(Integer, default=300)      # seconds between runs
    config = Column(Text, default="{}")          # JSON: type-specific config
    created_at = Column(DateTime, default=_now)
    updated_at = Column(DateTime, default=_now, onupdate=_now)

    runs = relationship("JobRun", back_populates="job", cascade="all, delete-orphan")
    project = relationship("Project")


class JobRun(Base):
    """Single execution record of a job."""
    __tablename__ = "job_runs"

    id = Column(String, primary_key=True, default=_uuid)
    job_id = Column(String, ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False, index=True)
    status = Column(Integer, default=0)          # JobRunStatus
    result = Column(Text, default="{}")          # JSON: type-specific output
    error = Column(Text, nullable=True)
    started_at = Column(DateTime, default=_now)
    finished_at = Column(DateTime, nullable=True)

    job = relationship("Job", back_populates="runs")


class Setting(Base):
    __tablename__ = "settings"

    key = Column(String, primary_key=True)
    value = Column(Text, default="")
    updated_at = Column(DateTime, default=_now, onupdate=_now)


class Skill(Base):
    """Centralized skill pool entry."""
    __tablename__ = "skills"

    id = Column(String, primary_key=True, default=_uuid)
    source_type = Column(String, nullable=False)   # "project" | "manual" | "external"
    source_id = Column(String, nullable=False)      # project_id, or "0" for manual/external
    name = Column(String, nullable=False)
    description = Column(Text, default="")
    content = Column(Text, default="")              # Markdown body (no YAML frontmatter)
    created_at = Column(DateTime, default=_now)
    updated_at = Column(DateTime, default=_now, onupdate=_now)

    project_links = relationship("ProjectSkill", back_populates="skill", cascade="all, delete-orphan")
    task_links = relationship("TaskSkill", back_populates="skill", cascade="all, delete-orphan")

    __table_args__ = (
        Index("uq_skill_source_name", "source_type", "source_id", "name", unique=True),
    )


class ProjectSkill(Base):
    """Association: which skills are linked to which project."""
    __tablename__ = "project_skills"

    id = Column(String, primary_key=True, default=_uuid)
    project_id = Column(String, ForeignKey("projects.id", ondelete="CASCADE"), nullable=False)
    skill_id = Column(String, ForeignKey("skills.id", ondelete="CASCADE"), nullable=False)
    created_at = Column(DateTime, default=_now)

    project = relationship("Project", back_populates="project_skills")
    skill = relationship("Skill", back_populates="project_links")

    __table_args__ = (
        Index("uq_project_skill", "project_id", "skill_id", unique=True),
    )


class TaskSkill(Base):
    """Extra skills selected for a specific task (beyond project defaults)."""
    __tablename__ = "task_skills"

    id = Column(String, primary_key=True, default=_uuid)
    task_id = Column(String, ForeignKey("tasks.id", ondelete="CASCADE"), nullable=False)
    skill_id = Column(String, ForeignKey("skills.id", ondelete="CASCADE"), nullable=False)
    created_at = Column(DateTime, default=_now)

    task = relationship("Task", back_populates="task_skills")
    skill = relationship("Skill", back_populates="task_links")

    __table_args__ = (
        Index("uq_task_skill", "task_id", "skill_id", unique=True),
    )


class McpServer(Base):
    """Global MCP (Model Context Protocol) server configuration for HTTP transport."""
    __tablename__ = "mcp_servers"

    id = Column(String, primary_key=True, default=_uuid)
    name = Column(String, nullable=False, unique=True)
    url = Column(String, nullable=False)
    headers = Column(Text, default="{}")  # JSON: {"Authorization": "Bearer ..."}
    enabled = Column(Integer, default=1)  # 1=enabled, 0=disabled
    created_at = Column(DateTime, default=_now)
    updated_at = Column(DateTime, default=_now, onupdate=_now)
